### ISSUE TITLE
Admin Merchants: Top Merchant's Best Day

### ISSUE THREAD

**Issue by lgsriclas** [lgsriclas/little-esty-shop#10]
As an admin,
When I visit the admin merchants index
Then next to each of the 5 merchants by revenue I see the date with the most revenue for each merchant.
And I see a label “Top selling date for <merchant name> was <date with most sales>"

Note: use the invoice date. If there are multiple days with equal number of sales, return the most recent day.

**Comment by chazsimons** [comment]
I think if we calculate the revenue for each invoice of our big 5 group we can then sort by the amount generated and pull the created by date to format. I think we can chain it onto the big_5 method potentially. I got something that works in console, but I'm not all the way there. I'll keep workshopping it.
